<?php use SPFPU\Core\{Csrf,View}; ?>
<div class="breadcrumb-bar"><nav class="breadcrumbs" aria-label="Jejak halaman"><a href="/">Kategori</a><span>/</span><span aria-current="page"><?=View::e($category['name'])?></span></nav><a class="button quiet breadcrumb-back" href="/" aria-label="Kembali ke senarai kategori"><span aria-hidden="true">←</span> Kembali</a></div>
<header class="page-head"><div><p class="eyebrow">Kategori</p><h1><?=View::e($category['name'])?></h1><p><?=View::e($category['description']?:'Senarai fail aktif di bawah kategori ini.')?></p></div><?php if($user['role']==='Admin'):?><div class="actions"><button class="button primary" data-dialog-open="fail-baru">Tambah fail</button><button class="button quiet" data-dialog-open="sunting-kategori">Sunting</button><button class="button danger-text" data-dialog-open="arkib-kategori">Arkib</button></div><?php endif?></header>
<form class="inline-search" method="get"><label class="sr-only" for="q">Cari fail</label><input id="q" name="q" value="<?=View::e($q)?>" placeholder="Cari kod rujukan atau nama fail"><button class="button quiet">Cari</button></form>
<section class="record-list folders"><?php if(!$folders):?><div class="empty"><span>00</span><h2>Tiada fail ditemui</h2><p>Ubah carian atau tambah fail baharu.</p></div><?php endif?><?php foreach($folders as $folder):?><a class="record-row" href="/fail/<?=(int)$folder['id']?>"><span class="ref-code"><?=View::e($folder['reference_code'])?></span><span class="row-main"><strong><?=View::e($folder['display_name'])?></strong><small><?=View::e($folder['description']?:'Tiada keterangan')?><?php if($folder['is_confidential']):?> · <em>Sulit</em><?php endif?></small></span><span class="row-metric"><b><?=(int)$folder['volume_count']?></b> Jilid</span><span class="row-metric"><b><?=(int)$folder['entry_count']?></b> Entri</span><span class="row-arrow">↗</span></a><?php endforeach?></section>
<?php if($user['role']==='Admin'):?>
<dialog id="sunting-kategori"><form method="post" action="/kategori/<?=(int)$category['id']?>/kemas-kini" class="dialog-form"><?=Csrf::field()?><header><div><p class="eyebrow">Kategori sedia ada</p><h2>Sunting kategori</h2></div><button type="button" class="icon-button" data-dialog-close aria-label="Tutup">×</button></header><label>Nama Kategori<input name="name" maxlength="150" value="<?=View::e($category['name'])?>" required></label><label>Keterangan <span>(pilihan)</span><textarea name="description" maxlength="500" rows="3"><?=View::e($category['description']??'')?></textarea></label><footer><button type="button" class="button quiet" data-dialog-close>Batal</button><button class="button primary">Simpan perubahan</button></footer></form></dialog>
<dialog id="fail-baru"><form method="post" action="/kategori/<?=(int)$category['id']?>/fail" class="dialog-form"><?=Csrf::field()?><header><div><p class="eyebrow">Fail + Jilid 1</p><h2>Tambah fail</h2></div><button type="button" class="icon-button" data-dialog-close>×</button></header><div class="form-grid"><label>Kod Rujukan<input name="reference_code" maxlength="100" required></label><label>Nama Fail<input name="display_name" maxlength="150" required></label></div><label>Keterangan <span>(pilihan)</span><textarea name="description" maxlength="500"></textarea></label><label class="check"><input type="checkbox" name="is_confidential" value="1"><span><strong>Fail sulit</strong><small>Tetapan ini kekal dan Staff memerlukan kebenaran individu.</small></span></label><footer><button type="button" class="button quiet" data-dialog-close>Batal</button><button class="button primary">Wujudkan fail</button></footer></form></dialog>
<dialog id="arkib-kategori"><form method="post" action="/arkib/kategori/<?=(int)$category['id']?>" class="dialog-form"><?=Csrf::field()?><h2>Arkib seluruh kategori?</h2><p>Semua fail, jilid dan entri di bawah kategori ini akan diarkibkan. Pemulihan hanya boleh dilakukan oleh pentadbir pangkalan data.</p><footer><button type="button" class="button quiet" data-dialog-close>Batal</button><button class="button danger">Arkib kategori</button></footer></form></dialog><?php endif?>
